{% set name = "openmmtorchplugin" %}
{% set version = "1.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/SCMusson/openmmtorchplugin/archive/v{{ version }}.tar.gz
  #sha256: 1d014dfc02ad0e424db2354f7e3c2a7d1e0a491e6bcdadbcc0d1ca058f60ed23

build:
  number: 3
  skip: true  # [cuda_compiler_version in (undefined, "None", "10.2", "11.0", "11.1")]
  skip: true  # [not unix]
  rpaths:
    - lib/
    - lib/plugins/
  #  - {{ SP_DIR }}/torch/lib
  run_exports:
    - {{ pin_subpackage(name) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - make
    - cmake
    - swig

  host:
    - openmm
    - python
    - pip
    - setuptools

  run:
    # openmm package is missing a run_export as of 9 June 2022
    - {{ pin_compatible('openmm', min_pin='x.x', max_pin='x.x') }}
    - python

test:
  imports:
    - torchexposedintegratorplugin
#  commands:
#    - test -f $PREFIX/include/TorchIntegratorKernels.h  # [unix]
about:
  home: https://github.com/SCMusson/openmmtorchplugin
  license: GPL-3.0-only
  license_file: LICENSE
  summary: OpenMM plugin to get forces for neural networks
  description: |
    This is a plugin for OpenMM that allows neural networks to 
    access force and energy. It is implemented with PyTorch.
  doc_url: https://github.com/SCMusson/openmmtorchplugin
  dev_url: https://github.com/SCMusson/openmmtorchplugin

extra:
  recipe-maintainers:
    - SCMusson
    - degiacom
